[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build && cp -r dist /app/dist_stable"]

[start]
cmd = "npx prisma migrate deploy && node /app/dist_stable/main"
